/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TaskTest {
	Task myTask;

	@Test
	public void Task_instantiatesCorrectly_true(){
		Task myTask = new Task("Mow the lawn");
	    assertEquals(true, myTask instanceof Task);
	}

   @Test
   public void Task_instantiatesWithDescription_String(){
   		new Task("Mow the Lawn");
	    assertEquals("Mow the lawn", myTask.getDescription());

   }
}
