/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.*;
import org.sql2o.*;

import static org.junit.Assert.*;

public class TaskTest {
		private static String USER = "sensei";
		private static String PASSWORD = "nomasana";


	//this test is run before any other test
	@Before
	public void setUp() {
	    DB.sql2o = new Sql2o("jdbc:postgresql://localhost:5432/to_do", USER, PASSWORD);
	}
	//this test is run after every other test
	  @After
	  public void tearDown() {
	    try(Connection con = DB.sql2o.open()) {
	      String sql = "DELETE FROM tasks *;";
	      con.createQuery(sql).executeUpdate();
	    }
	  }

	@Test
	public void Task_instantiatesCorrectly_true(){
		Task myTask = new Task("Mow the lawn");
	    assertEquals(true, myTask instanceof Task);
	}

    @Ignore
	@Test
   public void Task_instantiatesWithDescription_String(){
   		Task myTask = new Task("Mow the Lawn");
	    assertEquals("Mow the lawn", myTask.getDescription());

   }
}
